#!/bin/bash
sudo su -
sudo apt-get update -y
sudo apt-get install -y apache2 
sudo service apache2 start
sudo touch /var/www/html/index.html
sudo echo "<b>This is My Batch 5 Website</b>" > /var/www/html/index.html
